-- Import data for demo purposes

-- Insert demo data into stock table
INSERT INTO stock (NAME, DESCRIPTION, PRICE_IN_CENTS, LAST_UPDATE) VALUES ('VWOO1', 'VWOO1 description', 123, CURRENT_TIMESTAMP);
INSERT INTO stock (NAME, DESCRIPTION, PRICE_IN_CENTS, LAST_UPDATE) VALUES ('VWOO2', 'VWOO2 description', 124, CURRENT_TIMESTAMP);
INSERT INTO stock (NAME, DESCRIPTION, PRICE_IN_CENTS, LAST_UPDATE) VALUES ('VWOO3', 'VWOO3 description', 125, CURRENT_TIMESTAMP);
INSERT INTO stock (NAME, DESCRIPTION, PRICE_IN_CENTS, LAST_UPDATE) VALUES ('VWOO4', 'VWOO4 description', 126, CURRENT_TIMESTAMP);
INSERT INTO stock (NAME, DESCRIPTION, PRICE_IN_CENTS, LAST_UPDATE) VALUES ('VWOO5', 'VWOO5 description', 127, CURRENT_TIMESTAMP);


-- Insert demo data into stock_exchange table
INSERT INTO stock_exchange (NAME, DESCRIPTION, LIVE_IN_MARKET) VALUES ('AEX', 'AEX description', true);
INSERT INTO stock_exchange (NAME, DESCRIPTION, LIVE_IN_MARKET) VALUES ('NYSE', 'NYSE description', false);


-- Insert demo data into stock_EXCHANGE table
INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (1, 1, CURRENT_TIMESTAMP);
INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (1, 2, CURRENT_TIMESTAMP);
INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (1, 3, CURRENT_TIMESTAMP);
INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (1, 4, CURRENT_TIMESTAMP);
INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (1, 5, CURRENT_TIMESTAMP);

INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (2, 3, CURRENT_TIMESTAMP);
INSERT INTO stock_registration (EXCHANGE_ID, STOCK_ID, REGISTERED_AT) VALUES (2, 4, CURRENT_TIMESTAMP);